# Generated by Django 3.2.19 on 2023-06-14 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=30)),
                ('date_gathered', models.DateField()),
                ('source_link', models.CharField(max_length=10000)),
                ('macros_list', models.CharField(max_length=10000)),
                ('recipe_count', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=30)),
                ('source_link', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('height_in_inches', models.IntegerField(default=-1)),
                ('weight_in_lbs', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=30)),
                ('source_link', models.CharField(max_length=10000)),
                ('ingredients', models.ManyToManyField(to='nutri.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Mealplan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_link', models.CharField(max_length=10000)),
                ('meals', models.ManyToManyField(to='nutri.Meal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri.user')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='recipes',
            field=models.ManyToManyField(to='nutri.Recipe'),
        ),
        migrations.AddField(
            model_name='meal',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri.user'),
        ),
    ]
