# Generated by Django 3.2.19 on 2023-06-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='plan_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
