# Generated by Django 3.2.19 on 2023-06-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('muscle', models.CharField(max_length=30)),
                ('equipment', models.ManyToManyField(to='motion.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=10000)),
                ('category', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('height_in_inches', models.IntegerField(default=-1)),
                ('weight_in_lbs', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_ids', models.ManyToManyField(to='motion.Exercise')),
                ('user_id', models.ManyToManyField(to='motion.User')),
            ],
        ),
    ]
