# Generated by Django 3.2.19 on 2023-06-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutroutine',
            name='routine_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
